Update "magnetometer" permission reference
w3c/magnetometer pull request #74
Opened 2024-05-07 12:07 UTC by anssiko

This fixes duplicate definition.

Fix #73

2024-05-07 16:48 UTC, reillyeon requested changes
The reference to the "magnetometer" permission needs to be updated as well.

2024-05-07 16:48 UTC, reillyeon commented on index.bs
> +This specification defines a [=policy-controlled feature=] identified by the string "<code><a data-lt="magnetometer-feature">magnetometer</a></code>". Its [=default allowlist=] is "`self`".
Update the text since this specification doesn't define the feature anymore.

2024-05-07 18:14 UTC, anssiko commented on index.bs
> +This specification defines a [=policy-controlled feature=] identified by the string "<code><a data-lt="magnetometer-feature">magnetometer</a></code>". Its [=default allowlist=] is "`self`".
```suggestion
This specification utilizes the [=policy-controlled feature=] identified by the string "<code><a data-lt="magnetometer-feature">magnetometer</a></code>".
```

2024-05-08 20:15 UTC, reillyeon requested changes

2024-05-08 20:15 UTC, reillyeon commented on index.bs
> +This specification utilizes the [=policy-controlled feature=] identified by the string "<code><a data-lt="magnetometer-feature">magnetometer</a></code>".
The definition of the "magnetometer" permission below needs to be updated to a reference as well.

2024-05-13 09:16 UTC, anssiko commented
@reillyeon thanks for the review. I pushed a squashed and cleaned up version with improvements.

2024-05-14 23:52 UTC, reillyeon approved these changes

2024-05-15 07:00 UTC, merged